export const ADMIN_PROJECT_REVIEW_CONTENT = {
  reviewPanel: "لوحة مراجعة الإدارة",
  reviewerNotes: "إضافة ملاحظات المراجع",
  reviewerNotesPlaceholder: "اكتب ملاحظاتك للفريق...",
  approve: "الموافقة على المشروع",
  requestChanges: "طلب تغييرات",
  reject: "رفض المشروع",
  approvedBanner: "تمت الموافقة على المشروع",
  rejectedBanner: "تم رفض المشروع",
  changesRequestedBanner: "تم طلب تعديلات على المشروع",
  owner: "مالك المشروع",
  team: "أعضاء الفريق",
  additionalInfo: "معلومات إضافية",
  description: "وصف المشروع",
  summary: "ملخص المشروع",
  website: "الموقع الإلكتروني",
  media: "معرض الوسائط",
  attachments: "الملفات والمستندات",
  submissionDate: "تاريخ التقديم",
  lastUpdated: "آخر تحديث",
  projectId: "معرف المشروع",
  download: "تحميل",
  downloadPdf: "تحميل PDF",
  share: "مشاركة",
  preview: "معاينة",
  emptyMedia: "لا توجد وسائط مرفقة",
  emptyAttachments: "لا توجد مرفقات",
  emptyTeam: "لا يوجد أعضاء فريق",
  emptyDescription: "لا يوجد وصف متاح لهذا المشروع.",
  back: "العودة",
  approveSuccess: "تمت الموافقة على المشروع بنجاح",
  rejectSuccess: "تم رفض المشروع بنجاح",
  changesSuccess: "تم إرسال طلب التعديلات بنجاح",
  rejectConfirm: "هل أنت متأكد من رفض هذا المشروع؟",
  rejectConfirmAction: "تأكيد الرفض",
  rejectCancel: "إلغاء",
  updating: "جاري التحديث...",
  refreshing: "جاري تحديث البيانات...",
  updateError: "تعذر تحديث حالة المشروع. يرجى المحاولة مرة أخرى.",
  email: "البريد الإلكتروني",
  university: "الجامعة",
  linkedIn: "LinkedIn",
  role: "الدور",
  shareCopied: "تم نسخ رابط المشروع",
  shareUnsupported: "المشاركة غير مدعومة على هذا الجهاز",
  pdfHint: "استخدم طباعة الصفحة لحفظ PDF",
} as const;
