export const PROJECT_DETAILS_CONTENT = {
  pageTitleAr: "تفاصيل المشروع",
  pageTitleEn: "Project Details",
  reviewTitleAr: "مراجعة المشروع",
  reviewTitleEn: "Project Review",
  back: "رجوع",
  submissionDate: "تاريخ التقديم",
  statusTitle: "حالة المراجعة",
  statusTitleEn: "Review Status",
  ownerTitle: "صاحب المشروع",
  ownerTitleEn: "Project Owner",
  createdAt: "تاريخ الإنشاء",
  updatedAt: "آخر تحديث",
  infoTitle: "معلومات المشروع",
  infoTitleEn: "Project Information",
  projectName: "اسم المشروع",
  category: "التصنيف",
  description: "وصف المشروع",
  summary: "ملخص المشروع",
  teamCount: "أعضاء الفريق",
  filesCount: "الملفات المرفوعة",
  projectNumber: "رقم المشروع",
  mediaTitle: "الوسائط",
  mediaTitleEn: "Media",
  attachmentsTitle: "المرفقات",
  attachmentsTitleEn: "Attachments",
  teamTitle: "أعضاء الفريق",
  teamTitleEn: "Team Members",
  visitWebsite: "زيارة الموقع",
  linkedIn: "LinkedIn",
  download: "تحميل الملف",
  emptyMedia: "لا توجد وسائط مرفقة لهذا المشروع.",
  emptyAttachments: "لا توجد مرفقات لهذا المشروع.",
  emptyTeamMembers: "لا يوجد أعضاء فريق مسجلون لهذا المشروع.",
  emptyDescription: "لا يوجد وصف متاح.",
  emptySummary: "لا يوجد ملخص متاح.",
} as const;
